### ISSUE TITLE
Why `ignoreExtraKeys`?

### ISSUE THREAD

**Issue by Nyholm** [a-menshchikov/array-cast-explode-processors#1]
It is super rare that I see bundles using `->ignoreExtraKeys()`. https://github.com/nbgrp/env-bundle/blob/v1.0.2/src/DependencyInjection/Configuration.php#L55

I don't see that you are using extra keys in the extension class. Do you mind me asking why you need `->ignoreExtraKeys()`? It would be interesting to know.

**Comment by a-menshchikov** [comment]
@Nyholm thanks for your attention! This using was my mistake. =\

**Comment by Nyholm** [comment]
I see. Thank you for checking for me.
